insert into PHONE (price, model, color) values (59.31, 'Nokia 1100', 'Orange');
insert into PHONE (price, model, color) values (622.31, 'Nokia 1110', 'Orange');
insert into PHONE (price, model, color) values (452.7, 'Apple iPhone 6', 'Khaki');
insert into PHONE (price, model, color) values (267.38, 'Nokia 3210', 'Blue');
insert into PHONE (price, model, color) values (346.17, 'Nokia 1200', 'Mauv');
insert into PHONE (price, model, color) values (780.87, 'Nokia 6600', 'Turquoise');
insert into PHONE (price, model, color) values (217.55, 'Nokia 5230', 'Teal');
insert into PHONE (price, model, color) values (587.56, 'Samsung E1100', 'Mauv');
insert into PHONE (price, model, color) values (703.19, 'Nokia 2600', 'Puce');
insert into PHONE (price, model, color) values (330.1, 'Motorola RAZR V3', 'Pink');
insert into PHONE (price, model, color) values (357.32, 'Nokia 1600', 'Mauv');
insert into PHONE (price, model, color) values (404.42, 'Nokia 3310', 'Teal');
insert into PHONE (price, model, color) values (309.78, 'Nokia 1208', 'Indigo');
insert into PHONE (price, model, color) values (686.01, 'Samsung Galaxy S4', 'Crimson');
insert into PHONE (price, model, color) values (730.95, 'Nokia 6010', 'Purple');
insert into PHONE (price, model, color) values (620.89, 'Apple iPhone 5', 'Green');
insert into PHONE (price, model, color) values (758.64, 'Nokia 5130', 'Indigo');
insert into PHONE (price, model, color) values (233.46, 'Apple iPhone 4S', 'Fuscia');
insert into PHONE (price, model, color) values (604.39, 'Motorola StarTAC996', 'Mauv');
insert into PHONE (price, model, color) values (389.77, 'Motorola C200', 'Fuscia');
insert into PHONE (price, model, color) values (288.55, 'Samsung Galaxy S III', 'Goldenrod');
insert into PHONE (price, model, color) values (288.44, 'Apple iPhone 5S', 'Green');
insert into PHONE (price, model, color) values (117.99, 'Nokia 3100', 'Aquamarine');
insert into PHONE (price, model, color) values (490.26, 'Nokia 6230', 'Turquoise');
insert into PHONE (price, model, color) values (209.76, 'Apple iPhone 4', 'Maroon');
insert into PHONE (price, model, color) values (67.73, 'Samsung Galaxy S II', 'Fuscia');
insert into PHONE (price, model, color) values (213.38, 'Samsung Galaxy Note II', 'Purple');
insert into PHONE (price, model, color) values (108.47, 'Apple iPhone 3GS 5', 'Goldenrod');
insert into PHONE (price, model, color) values (547.94, 'Nokia 6270 Slider', 'Indigo');
insert into PHONE (price, model, color) values (368.96, 'Nokia 5200 Slider', 'Green');
insert into PHONE (price, model, color) values (565.1, 'Samsung E250', 'Yellow');
insert into PHONE (price, model, color) values (135.34, 'Samsung Star', 'Yellow');
insert into PHONE (price, model, color) values (393.27, 'Apple iPhone 5C', 'Blue');
insert into PHONE (price, model, color) values (344.09, 'HTC Thunderbolt', 'Yellow');
insert into PHONE (price, model, color) values (557.89, 'Nokia 6120', 'Fuscia');
insert into PHONE (price, model, color) values (543.97, 'Siemens M30', 'Crimson');
insert into PHONE (price, model, color) values (369.05, 'Nokia 3510', 'Indigo');
insert into PHONE (price, model, color) values (680.42, 'Nokia 6100', 'Blue');
insert into PHONE (price, model, color) values (182.83, 'Nokia 6610', 'Mauv');
insert into PHONE (price, model, color) values (625.31, 'Siemens A50', 'Teal');
insert into PHONE (price, model, color) values (528.09, 'Motorola V220', 'Violet');
insert into PHONE (price, model, color) values (126.81, 'Sony Ericsson K300', 'Fuscia');
insert into PHONE (price, model, color) values (326.08, 'Motorola PEBL U6', 'Violet');
insert into PHONE (price, model, color) values (375.69, 'Motorola SLVR L6', 'Blue');
insert into PHONE (price, model, color) values (630.98, 'Motorola SLVR L7', 'Red');
insert into PHONE (price, model, color) values (568.93, 'Sony Ericsson J300', 'Red');
insert into PHONE (price, model, color) values (280.96, 'Sony Ericsson K750', 'Maroon');
insert into PHONE (price, model, color) values (524.15, 'Motorola KRZR K1', 'Red');
insert into PHONE (price, model, color) values (588.14, 'Motorola V195', 'Mauv');
insert into PHONE (price, model, color) values (755.93, 'RIM BlackBerry Pearl', 'Yellow');
insert into PHONE (price, model, color) values (710.81, 'BenQ-Siemens S68', 'Yellow');
insert into PHONE (price, model, color) values (438.46, 'Sony Ericsson K310', 'Teal');
insert into PHONE (price, model, color) values (345.18, 'Sony Ericsson W810', 'Orange');
insert into PHONE (price, model, color) values (88.52, 'Nokia E71 Keyboard', 'Turquoise');
insert into PHONE (price, model, color) values (182.63, 'LG Chocolate', 'Turquoise');
insert into PHONE (price, model, color) values (464.37, 'Samsung S8300 Tocco Ultra', 'Violet');
insert into PHONE (price, model, color) values (410.33, 'Samsung Galaxy S5', 'Aquamarine');
insert into PHONE (price, model, color) values (68.76, 'LG Optimus One', 'Indigo');
insert into PHONE (price, model, color) values (264.32, 'Alcatel One Touch Mini OT-708', 'Khaki');