CREATE TABLE USERS (
  username VARCHAR(50) NOT NULL ,
  password VARCHAR(50) NOT NULL ,
  enabled NUMBER(1) NOT NULL
);
ALTER TABLE USERS ADD CONSTRAINT USERS_PK PRIMARY KEY ( username );

CREATE TABLE AUTHORITIES (
  username VARCHAR(50) NOT NULL ,
  authority VARCHAR(50) NOT NULL
);

ALTER TABLE AUTHORITIES ADD CONSTRAINT AUTHORITIES_USERS_FK FOREIGN KEY ( username ) REFERENCES USERS ( username );
CREATE UNIQUE INDEX IX_AUTH_USERNAME ON AUTHORITIES (username, authority);


